language: python
sudo: required
dist: trusty

env:
    global:
        - HI="ho"

matrix:
    include:
        - python: 3.4
          env: DEPLOY=0
        - python: 3.5
          env: DEPLOY=0
        - python: 3.6
          env: DEPLOY=0

before_install:
    - travis_retry pip install -U pip==9.0.1
    - travis_retry pip install --use-wheel pip-tools==1.8.0

install:
    - |
        if [ $TRAVIS_TAG ]; then
            pip install --use-wheel Cython==0.25.2
            mkdir wheelhouse
            pip wheel --no-binary :all: -r requirements.txt --wheel-dir=wheelhouse
            pip wheel -r requirements_dev.txt --wheel-dir=wheelhouse
            pip-sync --no-index --find-links wheelhouse/ requirements-dev.txt requirements.txt
        else
            pip-sync requirements-dev.txt requirements.txt
        fi

script:
    - pycodestyle --ignore=E501 --show-source xana.py
    - pycodestyle --ignore=E501 --show-source app

cache:
    apt: true
    pip: true
