language: python
sudo: required
dist: trusty
matrix:
    include:
        - python: 3.4
          env: DEPLOY=0
        - python: 3.5
          env: DEPLOY=0
        - python: 3.6
          env: DEPLOY=0

before_install:
    - travis_retry pip install -U pip==9.0.1
    - travis_retry pip install --use-wheel pip-tools==1.8.0

install:
    - pip-sync requirements-dev.txt requirements.txt
script:
    - pycodestyle --ignore=E501 --show-source xana.py
    - pycodestyle --ignore=E501 --show-source app
    - nosetests --with-coverage --cover-package=app/ --cover-tests
    - nosetests -v
cache:
    apt: true
    pip: true

after_success:
    - codecov
